.TH "devhelp" "1" "" "" "devhelp"
.SH "NAME"
.LP
devhelp \- An API documentation browser
.SH "SYNTAX"
.LP
devhelp [\fIOPTIONS\fP]
.SH "DESCRIPTION"
.LP
DevHelp is an API documentation browser for GNOME.
.br
.SH "OPTIONS"
.LP
.TP
\fB\-s, \-\-search\fR=KEYWORD
Search for a keyword (function, symbol...).
.LP
.TP
\fB\-a, \-\-search-assistant\fR=KEYWORD
Search and display any hit in the assistant window.
.SH "EXAMPLES"
.LP
To run this program the standard way type:
.LP
devhelp
.LP
If you would like to search for a function, type:
.LP
devhelp \-s search-string
.SH "AUTHORS"
.LP
DevHelp was written by Johan Dahlin <zilch.am@home.se>, Mikael Hallendal
<micke@codefactory.se>, Richard Hult <rhult@codefactory.se>, Frederic Peters
<fpeters@0d.be>, Aleksander Morgado <aleksander@aleksander.es>, and
Ignacio Casal Quinteiro <icq@gnome.org>.
.LP
This manual page is Copyright (c) 2001  Johan Dahlin <zilch.am@home.se> and Copyright(c) 2015  Frederic Peters <fpeters@0d.be>.
It has been written for the Debian GNU/Linux distribution and is distributed under the GNU General Public License. As such, it may be used, modified and distributed by anyone else as long as this copyright notice is preserved.
