/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/*
 * Interface for Devhelp
 *
 */

#include <Bonobo.idl>

module GNOME {
	module Devhelp {
		interface HelpBrowser : Bonobo::Unknown {
			void search            (in string str);
			void searchInNewWindow (in string str);
		};
	};
};
